Task_List/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/',include('task_app.urls'))
]

task_app/urls.py
from django.urls import path,re_path
from . import views
app_name='tasks'
urlpatterns=[
    path('create/',views.task_create,name='task_create'),
    path('',views.task_list,name='task_list'),
    re_path(r'^(?P<pk>\d+)/$',views.task_detail,name='task_detail'),
    re_path(r'^(?P<pk>\d+)/update/$', views.task_update,name='task_update'),
    re_path(r'^(?P<pk>\d+)/delete/$',views.task_delete,name='task_delete'),

]

# any ? 0or 1 occurance  <pk> primary key has digits

task_app/models.py
from django.db import models

# Create your models here.
class Status(models.TextChoices):
    UNSTARTED='u', "Not yet started"
    ONGOING='o', 'Ongoing'
    FINISHED='f','Finished'

class Task(models.Model):
    name=models.CharField(verbose_name="Task name",max_length=65,unique=True)
    t_date=models.DateField(verbose_name="Date")
    status=models.CharField(verbose_name="Task status", max_length=1,choices=Status.choices) #my status defined under status will come to this

    def __str__(self):
        return self.name

task_app/forms.py
from .models import Task
from django import forms

# need to define the form class
class TaskForm(forms.ModelForm):
    class Meta:
        model=Task
        fields="__all__"

task_app/views.py
from django.shortcuts import render,redirect
from django.urls import reverse #to tak the extension and new url should comin
from .models import Task
from .forms import TaskForm

# Create your views here.

#create
def task_create(request):
    if request.method == "POST": #checking if any thing in the form
        form=TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("tasks:task_list")) #redirecting it to  view ing the list
    else:
        form=TaskForm() #just display the empty form
    return render(request, "tasks/task_form.html", {'form':form,}) #only passing the html page

# list
def task_list(request):
   #tasks is given in forloop of html page
    tasks =Task.objects.all() #model.obejcts (all objects)
    return render(request, "tasks/task_list.html", {"tasks":tasks,})

# detail view

def task_detail(request,pk):
    task=Task.objects.get(pk=pk)
    return render(request, "tasks/task_detail.html",{"task":task,})

# update single task
def task_update(request,pk):
    task = Task.objects.get(pk=pk)
    if request.method == "POST":
        form = TaskForm(instance=task, data=request.POST) #instance=what ever fill in form is comming from task when saving requesting data from post
        if form.is_valid():
            form.save()
            return redirect(reverse("tasks:task_detail", args=[pk,]))
    else:
        form = TaskForm(instance=task)
    return render(request, "tasks/task_form.html", {"form":form,"object":task})

# delete
def task_delete(request,pk):
    task_obj = Task.objects.get(pk=pk)
    task_obj.delete()
    return redirect(reverse("tasks:task_list"))

templates/tasks/task_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>task detail</title>
</head>
<body>
<h1> task details</h1>
<P>Task name: {{task.name}} |<!--ID IS PASSED TO VIEW I AM TAKING THE NAME FORM THAT ID -->|
    <a href="{% url 'tasks:task_update' task.id  %}">update</a>
    <a href="{% url 'tasks:task_delete' task.id %}">Delete</a>

</P>

<p> Task Status: {{task.get_status_display}}</p>
<p>Date : {{task.t_date}}</p>
<br>
<p>
<a href="{% url 'tasks:task_list' %}">View all task</a>
<a href="{% url 'tasks:task_create' %}">create list</a>
</p>
</body>
</html>

templates/tasks/task_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% if object %} Edit task{% else %} create new task {% endif %}</title>
    <!--if object is there show title edit task else dispaly new task-->
</head>
<body>
<h2>{% if object %} Edit Task {% else %} create new task {% endif %}</h2>
<form action=" " method="post" enctype="multipart/form-data">
    {% csrf_token%}
    {{form.as_p}}
    <p><input type="submit" class="btn btn-success" value="submit"></p>
</form>
</body>
</html>

templates/tasks/task_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>task_list</title>
</head>
<body>
<h2>TASK LIST</h2>
{% for task in tasks %}
<!--counter default-->
   <p> {{ forloop.counter}}, {{task.name}},{{task.t_date}} - {{task.get_status_display}} <!-- we need th display text-->
   (<a href="{% url 'tasks:task_update' task.id %}">update</a> ) <!--from task -task update file take task id-->
    (<a href="{% url 'tasks:task_delete' task.id %}"> delete</a>)
       <!--this task:task_update this will got to the views file anad render the page from their -->
   </p>
{% endfor %}
<a href="{% url 'tasks:task_create' %}">Add New Task</a>

</body>
</html>